export const ProductCategoryActionTypes = {
    FETCH_ALL_PRODUCTCATEGORIES: "FETCH_ALL_PRODUCTCATEGORIES",
    GET_PRODUCTCATEGORY: "GET_PRODUCTCATEGORY",
    ADD_NEW_PRODUCTCATEGORY: "ADD_NEW_PRODUCTCATEGORY",
    EDIT_PRODUCTCATEGORY: "EDIT_PRODUCTCATEGORY",
    DELETE_PRODUCTCATEGORY: "DELETE_PRODUCTCATEGORY"
}