export const CategoryActionTypes = {
    FETCH_ALL_CATEGORIES: "FETCH_ALL_CATEGORIES",
    GET_CATEGORY: "GET_CATEGORY",
    ADD_NEW_CATEGORY: "ADD_NEW_CATEGORY",
    EDIT_CATEGORY: "EDIT_CATEGORY",
    DELETE_CATEGORY: "DELETE_CATEGORY"
}