export const ProductActionTypes = {
    FETCH_ALL_PRODUCTS: "FETCH_ALL_PRODUCTS",
    GET_PRODUCT: "GET_PRODUCT",
    ADD_NEW_PRODUCT: "ADD_NEW_PRODUCT",
    EDIT_PRODUCT: "EDIT_PRODUCT",
    DELETE_PRODUCT: "DELETE_PRODUCT"
}