export const WeightTypeActionTypes = {
    FETCH_ALL_WEIGHT_TYPES: "FETCH_ALL_WEIGHT_TYPES",
    GET_WEIGHT_TYPE: "GET_WEIGHT_TYPE",
    ADD_NEW_WEIGHT_TYPE: "ADD_NEW_WEIGHT_TYPE",
    EDIT_WEIGHT_TYPE: "EDIT_WEIGHT_TYPE",
    DELETE_WEIGHT_TYPE: "DELETE_WEIGHT_TYPE"
}